services:
  - type: web
    name: xhess-server
    env: docker
    dockerfilePath: ./Dockerfile.server
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: UPSTASH_REDIS_REST_URL
        value: https://lucky-hyena-138810.upstash.io
      - key: UPSTASH_REDIS_REST_TOKEN
        value: PRIVATE_TOKEN
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: check-and-mate-26c90
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@check-and-mate-26c90.iam.gserviceaccount.com
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://xhess-web.onrender.com

  - type: web
    name: xhess-web
    env: docker
    dockerfilePath: ./Dockerfile.web
    plan: free
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://xhess-server.onrender.com
